apiVersion: apps/v1
kind: Deployment
metadata:
  name: enclave-manager-pool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tee
  template:
    metadata:
      name: tee
      labels:
        app: tee
    spec:
      containers:
      - image: sammyne/hyperledger-tcf
        name: tee
        envFrom:
        - prefix: TCF_
          configMapRef:
            name: tcf-config
        command: ["/bin/bash"]
        args: ["$(TCF_HOME)/scripts/enclave_manager.sh"]
